//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelibWeb.VelibWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VelibWeb.IVelibService")]
    public interface IVelibService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetAllStationsByCity", ReplyAction="http://tempuri.org/IVelibService/GetAllStationsByCityResponse")]
        string GetAllStationsByCity(string nameOfCity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetAllStationsByCity", ReplyAction="http://tempuri.org/IVelibService/GetAllStationsByCityResponse")]
        System.Threading.Tasks.Task<string> GetAllStationsByCityAsync(string nameOfCity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetInfomationsOfStationByName", ReplyAction="http://tempuri.org/IVelibService/GetInfomationsOfStationByNameResponse")]
        string GetInfomationsOfStationByName(string nameOfCity, string numOfStation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetInfomationsOfStationByName", ReplyAction="http://tempuri.org/IVelibService/GetInfomationsOfStationByNameResponse")]
        System.Threading.Tasks.Task<string> GetInfomationsOfStationByNameAsync(string nameOfCity, string numOfStation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibServiceChannel : VelibWeb.IVelibService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibServiceClient : System.ServiceModel.ClientBase<VelibWeb.IVelibService>, VelibWeb.IVelibService {
        
        public VelibServiceClient() {
        }
        
        public VelibServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VelibServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAllStationsByCity(string nameOfCity) {
            return base.Channel.GetAllStationsByCity(nameOfCity);
        }
        
        public System.Threading.Tasks.Task<string> GetAllStationsByCityAsync(string nameOfCity) {
            return base.Channel.GetAllStationsByCityAsync(nameOfCity);
        }
        
        public string GetInfomationsOfStationByName(string nameOfCity, string numOfStation) {
            return base.Channel.GetInfomationsOfStationByName(nameOfCity, numOfStation);
        }
        
        public System.Threading.Tasks.Task<string> GetInfomationsOfStationByNameAsync(string nameOfCity, string numOfStation) {
            return base.Channel.GetInfomationsOfStationByNameAsync(nameOfCity, numOfStation);
        }
    }
}
