//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace VelibClient.VelibServer {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    // CODEGEN: 未处理命名空间“http://schemas.xmlsoap.org/ws/2004/09/policy”中的可选 WSDL 扩展元素“PolicyReference”。
    // CODEGEN: 未处理命名空间“http://www.w3.org/2005/08/addressing”中的可选 WSDL 扩展元素“EndpointReference”。
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="velib_IVelibService", Namespace="http://tempuri.org/")]
    public partial class VelibServiceClient : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllStationsByCityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInfomationsOfStationByNameOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public VelibServiceClient() {
            this.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12;
            this.Url = "http://localhost:8733/VelibWeb/VelibService/";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllStationsByCityCompletedEventHandler GetAllStationsByCityCompleted;
        
        /// <remarks/>
        public event GetInfomationsOfStationByNameCompletedEventHandler GetInfomationsOfStationByNameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IVelibService/GetAllStationsByCity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetAllStationsByCity([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nameOfCity) {
            object[] results = this.Invoke("GetAllStationsByCity", new object[] {
                        nameOfCity});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllStationsByCityAsync(string nameOfCity) {
            this.GetAllStationsByCityAsync(nameOfCity, null);
        }
        
        /// <remarks/>
        public void GetAllStationsByCityAsync(string nameOfCity, object userState) {
            if ((this.GetAllStationsByCityOperationCompleted == null)) {
                this.GetAllStationsByCityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllStationsByCityOperationCompleted);
            }
            this.InvokeAsync("GetAllStationsByCity", new object[] {
                        nameOfCity}, this.GetAllStationsByCityOperationCompleted, userState);
        }
        
        private void OnGetAllStationsByCityOperationCompleted(object arg) {
            if ((this.GetAllStationsByCityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllStationsByCityCompleted(this, new GetAllStationsByCityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IVelibService/GetInfomationsOfStationByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetInfomationsOfStationByName([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string nameOfCity, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string numOfStation) {
            object[] results = this.Invoke("GetInfomationsOfStationByName", new object[] {
                        nameOfCity,
                        numOfStation});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetInfomationsOfStationByNameAsync(string nameOfCity, string numOfStation) {
            this.GetInfomationsOfStationByNameAsync(nameOfCity, numOfStation, null);
        }
        
        /// <remarks/>
        public void GetInfomationsOfStationByNameAsync(string nameOfCity, string numOfStation, object userState) {
            if ((this.GetInfomationsOfStationByNameOperationCompleted == null)) {
                this.GetInfomationsOfStationByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfomationsOfStationByNameOperationCompleted);
            }
            this.InvokeAsync("GetInfomationsOfStationByName", new object[] {
                        nameOfCity,
                        numOfStation}, this.GetInfomationsOfStationByNameOperationCompleted, userState);
        }
        
        private void OnGetInfomationsOfStationByNameOperationCompleted(object arg) {
            if ((this.GetInfomationsOfStationByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInfomationsOfStationByNameCompleted(this, new GetInfomationsOfStationByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAllStationsByCityCompletedEventHandler(object sender, GetAllStationsByCityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllStationsByCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllStationsByCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetInfomationsOfStationByNameCompletedEventHandler(object sender, GetInfomationsOfStationByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInfomationsOfStationByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInfomationsOfStationByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591