//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelibConsoleClient.VelibServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VelibServer.IVelibService")]
    public interface IVelibService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetAllStationsByCity", ReplyAction="http://tempuri.org/IVelibService/GetAllStationsByCityResponse")]
        string GetAllStationsByCity(string nameOfCity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetAllStationsByCity", ReplyAction="http://tempuri.org/IVelibService/GetAllStationsByCityResponse")]
        System.Threading.Tasks.Task<string> GetAllStationsByCityAsync(string nameOfCity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetInfomationsOfStationByName", ReplyAction="http://tempuri.org/IVelibService/GetInfomationsOfStationByNameResponse")]
        string GetInfomationsOfStationByName(string nameOfCity, string numOfStation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetInfomationsOfStationByName", ReplyAction="http://tempuri.org/IVelibService/GetInfomationsOfStationByNameResponse")]
        System.Threading.Tasks.Task<string> GetInfomationsOfStationByNameAsync(string nameOfCity, string numOfStation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetRoute", ReplyAction="http://tempuri.org/IVelibService/GetRouteResponse")]
        string[] GetRoute(string origin, string destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetRoute", ReplyAction="http://tempuri.org/IVelibService/GetRouteResponse")]
        System.Threading.Tasks.Task<string[]> GetRouteAsync(string origin, string destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetHelp", ReplyAction="http://tempuri.org/IVelibService/GetHelpResponse")]
        string GetHelp(int plateform);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetHelp", ReplyAction="http://tempuri.org/IVelibService/GetHelpResponse")]
        System.Threading.Tasks.Task<string> GetHelpAsync(int plateform);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibServiceChannel : VelibConsoleClient.VelibServer.IVelibService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibServiceClient : System.ServiceModel.ClientBase<VelibConsoleClient.VelibServer.IVelibService>, VelibConsoleClient.VelibServer.IVelibService {
        
        public VelibServiceClient() {
        }
        
        public VelibServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VelibServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAllStationsByCity(string nameOfCity) {
            return base.Channel.GetAllStationsByCity(nameOfCity);
        }
        
        public System.Threading.Tasks.Task<string> GetAllStationsByCityAsync(string nameOfCity) {
            return base.Channel.GetAllStationsByCityAsync(nameOfCity);
        }
        
        public string GetInfomationsOfStationByName(string nameOfCity, string numOfStation) {
            return base.Channel.GetInfomationsOfStationByName(nameOfCity, numOfStation);
        }
        
        public System.Threading.Tasks.Task<string> GetInfomationsOfStationByNameAsync(string nameOfCity, string numOfStation) {
            return base.Channel.GetInfomationsOfStationByNameAsync(nameOfCity, numOfStation);
        }
        
        public string[] GetRoute(string origin, string destination) {
            return base.Channel.GetRoute(origin, destination);
        }
        
        public System.Threading.Tasks.Task<string[]> GetRouteAsync(string origin, string destination) {
            return base.Channel.GetRouteAsync(origin, destination);
        }
        
        public string GetHelp(int plateform) {
            return base.Channel.GetHelp(plateform);
        }
        
        public System.Threading.Tasks.Task<string> GetHelpAsync(int plateform) {
            return base.Channel.GetHelpAsync(plateform);
        }
    }
}
